[package]
name = "bmbp_orm_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true
[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
proc-macro2 = "1.0.56"
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
case_style = "0.2"
bmbp_orm = { path = "../bmbp_orm" }
bmbp_app_common = { path = "../bmbp_app_common" }
bmbp_app_utils = { path = "../bmbp_app_utils" }