[package]
name = "bmbp_abc"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
bmbp_vars = { workspace = true }
bmbp_bean = { workspace = true }
bmbp_orm = { workspace = true }
tera = { workspace = true }
rust-embed = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
salvo = { workspace = true }
