[package]
name = "bmbp_dev_manage"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "管理开发平台的元数据存储信息"
[dependencies]

bmbp_app_common = { path = "../bmbp_app_common" }
bmbp_app_utils = { path = "../bmbp_app_utils" }
bmbp_rdbc_orm = { path = "../bmbp_rdbc_orm" }
bmbp_rdbc_marco = { path = "../bmbp_rdbc_marco" }
reqwest = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
salvo = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }