[package]
name = "bmbp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# 全局参数存放
bmbp_app = { path = "../bmbp_app" }
tokio = { version = "1", features = ["full"] }
