[package]
name = "bmbp_rdbc_sql"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr ={ workspace = true }
# 时间库
chrono = "0"
tokio-postgres = { version = "0.7" ,features=["with-chrono-0_4"] }