[package]
name = "bmbp_rdbc_orm"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# sql
bmbp_rdbc_sql = { path = "../bmbp_rdbc_sql" }
bmbp_rdbc_macro = { path = "../bmbp_rdbc_macro" }
bmbp_app_common = { path = "../bmbp_app_common" }
# 日志
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
# 运行时
tokio = { version = "1", features = ["full"] }
async-trait = "0"
async_static = "0"
once_cell = "1"
# 数据库
tokio-postgres = "0.7"

