[package]
name = "bmbp_rdbc_orm"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# sql
bmbp_rdbc_sql = { path = "../bmbp_rdbc_sql" }
bmbp_rdbc_model = { path = "../bmbp_rdbc_model" }
bmbp_app_common = { path = "../bmbp_app_common" }
# 日志
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
# 运行时
tokio = { workspace = true }# 异步抽象
async-trait = { workspace = true }
async_static = { workspace = true }
once_cell = { workspace = true }
# 数据库
tokio-postgres =  { workspace = true }
# 序列化库
serde = { workspace = true }
serde_json ={ workspace = true }
# 时间库
chrono ={ workspace = true }
