[package]
name = "bmbp_extend_rule_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bmbp_app_common = {path="../bmbp_app_common"}
serde = { workspace = true }
serde_json = { workspace = true }
once_cell =  { workspace = true }