[workspace]
members = ["code/*"]
resolver = "2"
[workspace.package]
version = "0.0.1"
authors = ["Bmbp<rs_bmbp@163.com>"]
edition = "2021"
description = """
    A power full MIS template
"""
[workspace.dependencies]
salvo = { version = "*", features = ["default", "serve-static", "cors", "size-limiter","logging"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1"
uuid = { version = "1", features = ["serde", "v4"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
log = "*"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.73"
reqwest = "0.11"
toml = "0.8"
once_cell = "1"
svg = "*"
chrono = "0.4"
tera = "1.19.0"
rust-embed = "8.0.0"
async-once-cell = "0.5.3"
async_static = "0.1"
async-lock = "3.3.0"
syn = "2.0.48"
quote = "1"
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4"] }
serde_yaml = "*"
async-recursion = "*"
futures = "*"
convert_case = "*"
dashmap = "*"
regex = "*"
rand = "0.8.5"
case_style = "0.2"
md5 = "0.7"
rs_sha256 = "0.1.*"
libsm = "0.6.0"
base64 = "0.21.7"
