[workspace]
members = ["code/*"]
resolver = "2"
[workspace.package]
version = "0.0.1"
authors = ["Bmbp<rs_bmbp@163.com>"]
edition = "2021"
description = """
    A power full MIS template
"""
[workspace.dependencies]




