[workspace]
members = ["code/*"]
resolver = "2"
[workspace.package]
version = "0.0.1"
authors = ["Bmbp<rs_bmbp@163.com>"]
edition = "2021"
description = """
    A power full MIS template
"""
[workspace.dependencies]
salvo = { version = "*", features = ["default", "serve-static", "cors", "size-limiter", "logging"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
serde_repr = "*"
uuid = { version = "*", features = ["serde", "v4"] }
tracing = "*"
tracing-subscriber = { version = "*", features = ["env-filter"] }
log = "*"
tokio = { version = "*", features = ["full"] }
async-trait = "*"
reqwest = "*"
toml = "*"
once_cell = "*"
svg = "*"
chrono = "*"
tera = "*"
rust-embed = "*"
async-once-cell = "*"
async_static = "*"
async-lock = "*"
syn = { version = "2.0.48", features = ["full"] }
quote = "*"
tokio-postgres = { version = "*", features = ["with-chrono-0_4"] }
serde_yaml = "*"
async-recursion = "*"
futures = "*"
convert_case = "*"
dashmap = "*"
regex = "*"
rand = "*"
case_style = "*"
md5 = "*"
rs_sha256 = "*"
libsm = "*"
base64 = "*"
