[workspace]
members = ["code/*"]
resolver = "2"
[workspace.package]
version = "0.0.1"
authors = ["Bmbp<rs_bmbp@163.com>"]
edition = "2021"
description = """
    A power full MIS template
"""
[workspace.build]
openssl = "/opt/homebrew/Cellar/openssl@3/3.3.0"
[workspace.dependencies]
# 注意：版本号被保留为 '*' 或具体版本，根据你的需求。
async-lock = "*"
async-once-cell = "*"
async-recursion = "*"
async-static = "*"
async-trait = "*"
async_trait = "*" # 注意：这是 async_trait 的正确键名
base64 = "*"
case_style = "*"
chrono = "*"
convert_case = "*"
dashmap = "*"
futures = "*"
lazy_static = "*"
libsm = "*"
log = "*"
md5 = "*"
openssl = { version = "0.10.64", features = ["vendored"] }
openssl-sys = "0.9.102"
once_cell = "*"
rand = "*"
regex = "*"
reqwest = "*"
rs_sha256 = "*"
rust-embed = "*"
salvo = { version = "*", features = ["default", "serve-static", "cors", "size-limiter", "logging"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
serde_repr = "*"
serde_yaml = "*"
svg = "*"
syn = { version = "2.0.72", features = ["full", "parsing", "printing", "proc-macro", "clone-impls"] }
tokio = { version = "*", features = ["full"] }
tokio-postgres = { version = "*", features = ["with-chrono-0_4"] }
tracing = "*"
tracing-subscriber = { version = "*", features = ["env-filter"] }
toml = "*"
tera = "*"
quote = "*"
uuid = { version = "*", features = ["serde", "v4"] }
