[workspace]
members = ["crates/*"]
resolver = "2"
[workspace.package]
version = "0.0.1"
edition = "2021"
authors = ["bmbp<rs_bmbp.163.com>"]
description = "BMBP"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/bmbper/bmbp"
repository = "https://github.com/bmbper/bmbp"
documentation = "https://github.com/bmbper/bmbp"
[workspace.dependencies]

