code: "bmbpDev" # 接口分组编码
title: "研发工具" # 接口分组标题
desc: "用于硬编码提供开发工具中应用管理、功能管理、数据模型、接口模型的数据管理" # 接口说明
metaApiGroup: # 元数据配置的接口分组
  - code: "bmbpDevApp" #接口分组编码
    title: "应用管理" # 接口分组标题
    desc: "应用管理模块的API接口集合" # 接口分组捞述
    apiGroup:
      queryApi:
        - code: bmbpDevAppQuery
          title: 应用查询接口
          desc:  根据状态、应用名称查询应用信息
          # 接口参数
          params:
            - name: appStatus # 参数名称
              title: 应用状态 # 参数标题
              desc: 应用状态 # 参数说明
              from: body # 参数来源
              paramType: string # 参数类型
              multiParam: false # 多个参数值
              allowEmpty: "null" # 允许为空类型
              regex: [] # 正则验证规则
            - name: appQuery
              title: 查询条件
              desc: 应用名称或应用标题
              from: body
              paramType: string
              multiParam: false
              allowEmpty: "null"
              regex: [ ]
          # 模型数据
          model:
            - code: "bmbpDevApp" # 模型编码
              title: "应用管理数据模型" # 模型标题
              schema: "BMBP" # 模型模式
              tableName: "BMBP_DEV_APP" # 对应表名
              field:
                - code: "appCode" #编码
                  name: "APP_CODE" #列名称
                  title: "应用编码" # 列标题
                - code: "appName" #编码
                  name: "APP_NAME" #列名称
                  title: "应用名称" # 列标题
                - code: "appDesc" #编码
                  name: "APP_DESC" #列名称
                  title: "应用说明" # 列标题
                - code: "appIcon" #编码
                  name: "APP_ICON" #列名称
                  title: "应用图片" # 列标题
                - code: "appType" #编码
                  name: "APP_TYPE" #列名称
                  title: "应用类型" # 列标题
                - code: "appURL" #编码
                  name: "APP_URL" #列名称
                  title: "应用地址" # 列标题
                - code: "appStatus" #编码
                  name: "APP_STATUS" #列名称
                  title: "应用状态" # 列标题
                - code: "appVersion" #编码
                  name: "APP_VERSION" #列名称
                  title: "应用版本" # 列标题
                - code: "appKey" #编码
                  name: "APP_KEY" #列名称
                  title: "加密标识" # 列标题
                - code: "appSec" #编码
                  name: "APP_SEC" #列名称
                  title: "密钥" # 列标题
              virtualField:
                - code: "appNameVersion"
                  title: "应用名称版本"
                  type: "concat" # concat 连接 | sum 计算 | count 统计| sql 语句|
                  field:
                    - type: "column" # column 列 | value  值 | sql 语句
                      value: "appName" # 值
                    - type:  "column"
                      value: "appVersion"
                    - type: "value"
                      value: "_bmbp"
              filter:
                expressType: "AND" # AND | OR | CUSTOM
                expressValue: # CUSTOM 时
                field:
                  - code: "appStatus" #编码
                    name: "APP_STATUS" #列名称
                    title: "应用状态" # 列标题
                    compareType: "=" # = |!= | > | >= | < | <= | like | not like | like_l | like_r | not like_l | not like_r |in | not_in |
                    compareValue:
                      - type: "param" # param 参数名称 | func 自定义方法| vars 内置参数 |
                        value: "appStatus" # 参数名称
                        handle: "" # 处理 array_in | split_in | custom |
                  - code: "appName" #编码
                      name: "APP_NAME" #列名称
                      title: "应用名称" # 列标题
                      compareType: "like" # = |!= | > | >= | < | <= | like | not like | like_l | like_r | not like_l | not like_r |in | not_in |
                      compareValue:
                        - type: "param" # param 参数名称 | func 自定义方法| vars 内置参数 |
                          value: "appName" # 参数名称
                          handle: "" # 处理 array_in | split_in | custom |
                  - code: "appCode" #编码
                      name: "APP_CODE" #列名称
                      title: "应用编码" # 列标题
                      compareType: "like" # = |!= | > | >= | < | <= | like | not like | like_l | like_r | not like_l | not like_r |in | not_in |
                      compareValue:
                        - type: "param" # param 参数名称 | func 自定义方法| vars 内置参数 |
                          value: "appName" # 参数名称
                          handle: "" # 处理 array_in | split_in | custom |
              having: []
              order:
                - name: "appName" # 字段名称
                  title: "应用名称" # 字段标题
                  orderType: "ASC" #排序类型
                  orderNum: 1 # 排序顺序
                - name: "appCode" # 字段名称
                  title: "应用编码" # 字段标题
                  orderType: "ASC" #排序类型
                  orderNum: 2 # 排序顺序
          rule:
            - order: 0
              type: dict
              field:
                - name: "appType"
                  value: "appType"
                - name: "appStatus"
                  value: "appStatus"
            - order: 1
              type: format
              field:
                - name: ""
                  value: ""
                  type: ""
          extend: []
          modelRef: []
          filter: { }
          order: []
          having: []
          dataRef: {}
