[package]
name = "bmbp_app"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
[dependencies]
salvo = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
bmbp_orm = { workspace = true }
bmbp_sql = { workspace = true }
bmbp_ui_lib = { workspace = true }
bmbp_ui_theme = { workspace = true }
bmbp_home = { workspace = true }
bmbp_framework = { workspace = true }
bmbp_vars = { workspace = true }
bmbp_app_auth = { workspace = true }
rust-i18n = { workspace = true }
rust-embed = { workspace = true }