[package]
name = "bmbp_macro"
version = "0.1.0"
edition = "2021"
[lib]
proc-macro = true
[dependencies]

bmbp_app_common = { path = "../bmbp_app_common" }
bmbp_app_utils = { path = "../bmbp_app_utils" }
# 宏语法解析器
syn = "2.0.48"
quote = "1"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
