[package]
name = "bmbp_macro"
version = "0.1.0"
edition = "2021"
[lib]
proc-macro = true
[dependencies]

bmbp_app_common = { path = "../bmbp_app_common" }
bmbp_app_utils = { path = "../bmbp_app_utils" }
# 宏语法解析器
syn = { workspace = true }
quote = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
