[package]
name = "bmbp_bpm_identity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# 应用链路跟踪
tracing = "0.1"
tracing-subscriber = "0.3"