[package]
name = "bmbp_orm"
version = "0.1.0"
edition = "2021"
description = "数据库ORM"
[dependencies]

# 应用链路跟踪
tracing = "0.1"
tracing-subscriber = "0.3"
# 序列化
serde = { version = "1", features = ["derive"] }
serde_json = "1"
case_style = "0.2"
# 日期
chrono = "0.4"
# 全局变量
once_cell = "1"
# 正则解析
regex = "1"
time = "0.3"
byte-io = "0.1"

# SQL 解析器，用于提取语法参数
sqlparser = "0.27"

tokio-postgres = { version = "0.7", features = ["with-serde_json-1"] }

tokio = { version = "1", features = ["full"] }

async-trait = "0.1"
# 应用工具类
bmbp_app_common = { path = "../bmbp_app_common" }
bmbp_app_utils = { path = "../bmbp_app_utils" }
