[package]
name = "bmbp_vars"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "存储全局变量"
[dependencies]
rust-i18n = { workspace = true }
rust-embed = { workspace = true }

