[package]
name = "bmbp_app_file"
version = "0.1.0"
edition = "2021"
description = "应用中附件和静态文件的管理模块"
[dependencies]

axum = "0.6"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.3", features = ["fs", "trace"] }
tower = { version = "0.4", features = ["util"] }