[package]
name = "bmbp_app_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1"

axum = "0.6"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.3", features = ["fs", "trace"] }
tower = { version = "0.4", features = ["util"] }


once_cell = "1"
async-once-cell = "0.4"
async_static = "0.1"
async-lock = "2"
async-trait = "0.1"