[package]
name = "bmbp_rdbc"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bmbp_rdbc_model = { path = "../bmbp_rdbc_model" }
bmbp_rdbc_orm = { path = "../bmbp_rdbc_orm" }
bmbp_rdbc_sql = { path = "../bmbp_rdbc_sql" }
