[package]
name = "bmbp_marco_rdbc"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true
[dependencies]
quote = { workspace = true }
syn = { workspace = true }
proc-macro2 = "1.0.82"
case_style = { workspace = true }
serde = { workspace = true }

bmbp_rdbc_orm = { path = "../bmbp_rdbc_orm" }
bmbp_app_common = { path = "../bmbp_app_common" }
bmbp_marco_util = { path = "../bmbp_marco_util" }

salvo = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }