groupCode: "bmbpDev" # 数据模型分组，一般以功能模块为单位,以UUID生成
groupName: "bmbpDev" # 英文助记符
groupTitle: "应用开发模块" # 标题
groupDesc: "应用开发模块中管理的数据模型" # 描述
models: # 具体的数据模型列表
  - code: "bmbpDevApp" # UUID生成的约束
    title: "应用数据模型" # 中文名称
    desc: "存放应用数据" # 描述该模型的数据
    schema: "BMBP" # 数据库模式名
    tableName: "BMBP_DEV_APP" # 表名称
    tableComment: "应用信息表" # 表注释
    columns:
      - code: "appCode" #编码
        name: "APP_CODE" #列名称
        title: "应用编码" # 列标题
        type: "STRING" # 列类型
        length: 36 # 列长度
        scale: 0 #列精度，小数位数，当type为NUMBER时生效
        default: "" # 默认值
      - code: "appName" #编码
        name: "APP_NAME" #列名称
        title: "应用名称" # 列标题
        type: "STRING" # 列类型
        length: 64 # 列长度
        scale: 0 #列精度，小数位数，当type为NUMBER时生效
        default: "" # 默认值
      - code: "appDesc" #编码
        name: "APP_DESC" #列名称
        title: "应用说明" # 列标题
        type: "STRING" # 列类型
        length: 128 # 列长度
        scale: 0 #列精度，小数位数，当type为NUMBER时生效
        default: "" # 默认值
      - code: "appIcon" #编码
        name: "APP_ICON" #列名称
        title: "应用图片" # 列标题
        type: "STRING" # 列类型
        length: 4096 # 列长度
        scale: 0 #列精度，小数位数，当type为NUMBER时生效
        default: "" # 默认值
      - code: "appType" #编码
        name: "APP_TYPE" #列名称
        title: "应用类型" # 列标题
        type: "STRING" # 列类型
        length: 32 # 列长度
        scale: 0 #列精度，小数位数，当type为NUMBER时生效
        default: "" # 默认值
      - code: "appURL" #编码
        name: "APP_URL" #列名称
        title: "应用地址" # 列标题
        type: "STRING" # 列类型
        length: 256 # 列长度
        scale: 0 #列精度，小数位数，当type为NUMBER时生效
        default: "" # 默认值
      - code: "appStatus" #编码
        name: "APP_STATUS" #列名称
        title: "应用状态" # 列标题
        type: "STRING" # 列类型
        length: 32 # 列长度
        scale: 0 #列精度，小数位数，当type为NUMBER时生效
        default: "" # 默认值
      - code: "appVersion" #编码
        name: "APP_VERSION" #列名称
        title: "应用版本" # 列标题
        type: "STRING" # 列类型
        length: 32 # 列长度
        scale: 0 #列精度，小数位数，当type为NUMBER时生效
        default: "" # 默认值
      - code: "appKey" #编码
        name: "APP_KEY" #列名称
        title: "加密标识" # 列标题
        type: "STRING" # 列类型
        length: 128 # 列长度
        scale: 0 #列精度，小数位数，当type为NUMBER时生效
        default: "" # 默认值
      - code: "appSec" #编码
        name: "APP_SEC" #列名称
        title: "密钥" # 列标题
        type: "STRING" # 列类型
        length: 128 # 列长度
        scale: 0 #列精度，小数位数，当type为NUMBER时生效
        default: "" # 默认值
    index: # 索引约束配置
      primary: # 主键约束
        name: "bmbpDevAppPrimary" # 主键名称
        field: # 主建字段 ["",""] 字段数组，对应列code
          - recordId
      unique: # 惟一约束
          name: "bmbpDevAppUnique"
          field:
            - tableName
            - schema
      normal: # 正常约束
          name: "bmbpDevAppNormal"
          filed:
            - code
            - tableName
            - schema
