[package]
name = "bmbp_dev_generate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

once_cell = { workspace = true }
log = { workspace = true }
bmbp_app_common = { path = "../bmbp_app_common" }
bmbp_app_utils = { path = "../bmbp_app_utils" }
serde = { workspace = true }
serde_json = { workspace = true }