[package]
name = "bmbp_dev_generate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

once_cell = "1"
log = "0.4"
bmbp_util = { path = "../bmbp_util" }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"