[package]
name = "bmbp_app_portal"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "门户应用，网站介绍"
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
[dependencies]

bmbp_app_common = { path = "../bmbp_app_common" }
bmbp_app_utils = { path = "../bmbp_app_utils" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
salvo = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }