[package]
name = "bmbp_rule"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
# 正则表达式
regex = "1"
fancy-regex = "0.10"
# 规则引擎
rule = "0.1"
once_cell = "1"