[package]
name = "bmbp"
version = "0.1.0"
edition = "2021"
[dependencies]
bmbp_app = { workspace = true }
tokio = { workspace = true }
rust-i18n = { workspace = true }
rust-embed = { workspace = true }