[package]
name = "bmbp_dev_engine"
version = "0.1.0"
edition = "2021"

[dependencies]

bmbp_dev_dsl = { path = "../bmbp_dev_dsl" }
# 序列化
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
async-recursion = { workspace = true }
futures = { workspace = true }
convert_case = { workspace = true }
dashmap = { workspace = true }
# 全局变量
tokio = { workspace = true }
once_cell = { workspace = true }
# 正则解析
regex = { workspace = true }
# 数据库封装

