[package]
name = "bmbp_dev_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
# 序列化
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"

# web框架

# 异步递归
async-recursion = "1"
futures = { version = "0.3", features = ["thread-pool"] }
tokio = { version = "1.32.0", features = ["full"] }
# 并发MAP
dashmap = "5"
# 全局变量
once_cell = "1"
convert_case = "0.6"
# 正则解析
regex = "1"

bmbp_dev_dsl = { path = "../bmbp_dev_dsl" }
# 数据库封装
bmbp_orm = { path = "../bmbp_orm" }
