[bmbp]
[bmbp.app]
code = "bmbp"
name = "Bmbp低代码平台"
title = "Bmbp低代码平台"
login = "Bmbp低代码平台"
copy_right = "Bmbp低代码平台 版权信息"
env = "dev"
log_level = "debug"
[bmbp.server]
host = ""
port = 8011
[bmbp.datasource]
driver = "postgres"
host = "127.0.0.1"
port = 5432
database = "bmbp"
schema = "public"
username = "bmbp"
password = "zgk0130!"
ignore_case = true
