[package]
name = "bmbp_rdbc_macro"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.195", features = ["derive"] }
bmbp_rdbc_sql = { path = "../bmbp_rdbc_sql" }

# 日志
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }

# 数据库
tokio-postgres = { version = "0.7" ,features=["with-chrono-0_4"] }
# 时间库
chrono = "0"
log = "0.4.20"