[package]
name = "bmbp_dev_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bmbp_app_utils = { path = "../bmbp_app_utils" }
bmbp_app_common = { path = "../bmbp_app_common" }
bmbp_dev_engine = { path = "../bmbp_dev_engine" }
salvo = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
svg = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }



