[package]
name = "bmbp_rdbc_meta"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "管理数据库元数据，查询表结构信息、生成建表表语句、更新语句，根据元数据模型对比差异，不与直接与数据库连接"
[dependencies]
serde = { workspace = true }
bmbp_bean_marco = { path = "../bmbp_bean_marco" }