[package]
name = "bmbp_app_auth"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "认证模块"
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
[dependencies]
bmbp_auth = { workspace = true }
bmbp_vars = { workspace = true }
salvo = { workspace = true }
wildmatch = "2.4.0"
rust-embed = { workspace = true }
bmbp_abc = { workspace = true }
