[package]
name = "bmbp_rdbc_marco"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true
[dependencies]
quote = { workspace = true }
syn = { workspace = true }
proc-macro2 = "*"
case_style = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
bmbp_rdbc_orm = { path = "../bmbp_rdbc_orm" }
bmbp_app_common = { path = "../bmbp_app_common" }
salvo = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }